version: '3.6'
services:
  postgre:
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/ # persist data even if container shuts down
    env_file:
      - database.env # configure postgres
    build: C:\Docker

volumes:
    postgres: # named volumes can be managed easier using docker-compose
        name: postgres
      
